-- MySQL Script generated by MySQL Workbench
-- Tue Oct 21 15:42:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema oodbs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oodbs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oodbs` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `oodbs` ;

-- -----------------------------------------------------
-- Table `oodbs`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oodbs`.`organization` (
  `organization_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `contact_email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`organization_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oodbs`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oodbs`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `organization_id` INT NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) NULL DEFAULT NULL,
  `full_name` VARCHAR(255) NULL DEFAULT NULL,
  `role` VARCHAR(50) NULL DEFAULT NULL,
  `phone_num` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `organization_id` (`organization_id` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `oodbs`.`organization` (`organization_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oodbs`.`bus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oodbs`.`bus` (
  `bus_id` INT NOT NULL AUTO_INCREMENT,
  `organization_id` INT NULL DEFAULT NULL,
  `driver_id` INT NULL DEFAULT NULL,
  `plate_number` VARCHAR(50) NULL DEFAULT NULL,
  `capacity` INT NULL DEFAULT NULL,
  `company` VARCHAR(50) NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`bus_id`),
  INDEX `organization_id` (`organization_id` ASC) VISIBLE,
  INDEX `driver_id` (`driver_id` ASC) VISIBLE,
  CONSTRAINT `bus_ibfk_1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `oodbs`.`organization` (`organization_id`),
  CONSTRAINT `bus_ibfk_2`
    FOREIGN KEY (`driver_id`)
    REFERENCES `oodbs`.`users` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oodbs`.`bus_seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oodbs`.`bus_seats` (
  `seat_id` INT NOT NULL AUTO_INCREMENT,
  `bus_id` INT NULL DEFAULT NULL,
  `seat_number` VARCHAR(10) NULL DEFAULT NULL,
  `is_reserved` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`seat_id`),
  INDEX `bus_id` (`bus_id` ASC) VISIBLE,
  CONSTRAINT `bus_seats_ibfk_1`
    FOREIGN KEY (`bus_id`)
    REFERENCES `oodbs`.`bus` (`bus_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oodbs`.`pickup_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oodbs`.`pickup_location` (
  `pickup_id` INT NOT NULL AUTO_INCREMENT,
  `organization_id` INT NULL DEFAULT NULL,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `latitude` FLOAT NULL DEFAULT NULL,
  `longitude` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`pickup_id`),
  INDEX `organization_id` (`organization_id` ASC) VISIBLE,
  CONSTRAINT `pickup_location_ibfk_1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `oodbs`.`organization` (`organization_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oodbs`.`bus_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oodbs`.`bus_services` (
  `service_id` INT NOT NULL AUTO_INCREMENT,
  `bus_id` INT NULL DEFAULT NULL,
  `pickup_id` INT NULL DEFAULT NULL,
  `service_date` TIMESTAMP NULL DEFAULT NULL,
  `isAmShift` TINYINT(1) NULL DEFAULT NULL,
  `isPmShift` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`service_id`),
  INDEX `bus_id` (`bus_id` ASC) VISIBLE,
  INDEX `pickup_id` (`pickup_id` ASC) VISIBLE,
  CONSTRAINT `bus_services_ibfk_1`
    FOREIGN KEY (`bus_id`)
    REFERENCES `oodbs`.`bus` (`bus_id`),
  CONSTRAINT `bus_services_ibfk_2`
    FOREIGN KEY (`pickup_id`)
    REFERENCES `oodbs`.`pickup_location` (`pickup_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oodbs`.`organization_locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oodbs`.`organization_locations` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `organization_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `latitude` FLOAT NULL DEFAULT NULL,
  `longitude` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`location_id`),
  INDEX `organization_id` (`organization_id` ASC) VISIBLE,
  CONSTRAINT `organization_locations_ibfk_1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `oodbs`.`organization` (`organization_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 283
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oodbs`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oodbs`.`schedule` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `service_id` INT NULL DEFAULT NULL,
  `departure_time` TIMESTAMP NULL DEFAULT NULL,
  `arrival_time` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`schedule_id`),
  INDEX `service_id` (`service_id` ASC) VISIBLE,
  CONSTRAINT `schedule_ibfk_1`
    FOREIGN KEY (`service_id`)
    REFERENCES `oodbs`.`bus_services` (`service_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oodbs`.`tier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oodbs`.`tier` (
  `tier_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`tier_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oodbs`.`passenger_requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oodbs`.`passenger_requests` (
  `request_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `bus_id` INT NULL DEFAULT NULL,
  `pickup_id` INT NULL DEFAULT NULL,
  `location_id` INT NULL DEFAULT NULL,
  `tier_id` INT NULL DEFAULT NULL,
  `passenger_count` VARCHAR(50) NULL DEFAULT NULL,
  `request_status` TINYINT(1) NULL DEFAULT NULL,
  `schedule_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`request_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `bus_id` (`bus_id` ASC) VISIBLE,
  INDEX `pickup_id` (`pickup_id` ASC) VISIBLE,
  INDEX `location_id` (`location_id` ASC) VISIBLE,
  INDEX `tier_id` (`tier_id` ASC) VISIBLE,
  INDEX `fk_passenger_requests_schedule` (`schedule_id` ASC) VISIBLE,
  CONSTRAINT `fk_passenger_requests_schedule`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `oodbs`.`schedule` (`schedule_id`),
  CONSTRAINT `passenger_requests_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `oodbs`.`users` (`user_id`),
  CONSTRAINT `passenger_requests_ibfk_2`
    FOREIGN KEY (`bus_id`)
    REFERENCES `oodbs`.`bus` (`bus_id`),
  CONSTRAINT `passenger_requests_ibfk_3`
    FOREIGN KEY (`pickup_id`)
    REFERENCES `oodbs`.`pickup_location` (`pickup_id`),
  CONSTRAINT `passenger_requests_ibfk_4`
    FOREIGN KEY (`location_id`)
    REFERENCES `oodbs`.`organization_locations` (`location_id`),
  CONSTRAINT `passenger_requests_ibfk_5`
    FOREIGN KEY (`tier_id`)
    REFERENCES `oodbs`.`tier` (`tier_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oodbs`.`routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oodbs`.`routes` (
  `route_id` INT NOT NULL AUTO_INCREMENT,
  `schedule_id` INT NULL DEFAULT NULL,
  `request_id` INT NULL DEFAULT NULL,
  `tier_id` INT NULL DEFAULT NULL,
  `stop_order` INT NULL DEFAULT NULL,
  `eta` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`route_id`),
  INDEX `schedule_id` (`schedule_id` ASC) VISIBLE,
  INDEX `request_id` (`request_id` ASC) VISIBLE,
  INDEX `tier_id` (`tier_id` ASC) VISIBLE,
  CONSTRAINT `routes_ibfk_1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `oodbs`.`schedule` (`schedule_id`),
  CONSTRAINT `routes_ibfk_2`
    FOREIGN KEY (`request_id`)
    REFERENCES `oodbs`.`passenger_requests` (`request_id`),
  CONSTRAINT `routes_ibfk_3`
    FOREIGN KEY (`tier_id`)
    REFERENCES `oodbs`.`tier` (`tier_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oodbs`.`seat_assignments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oodbs`.`seat_assignments` (
  `assignment_id` INT NOT NULL AUTO_INCREMENT,
  `request_id` INT NULL DEFAULT NULL,
  `seat_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`assignment_id`),
  INDEX `request_id` (`request_id` ASC) VISIBLE,
  INDEX `seat_id` (`seat_id` ASC) VISIBLE,
  CONSTRAINT `seat_assignments_ibfk_1`
    FOREIGN KEY (`request_id`)
    REFERENCES `oodbs`.`passenger_requests` (`request_id`),
  CONSTRAINT `seat_assignments_ibfk_2`
    FOREIGN KEY (`seat_id`)
    REFERENCES `oodbs`.`bus_seats` (`seat_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
